services:
  db:
    image: postgres:16
    container_name: levita-db
    restart: always
    environment:
      POSTGRES_DB: levita_kpi_system
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  levita-monitoring:
    build: .
    container_name: levita-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CREDENTIALS: /app/credentials.json
      GOOGLE_SHEET_ID: ${GOOGLE_SHEET_ID}
      POOL_SIZE: 6
    volumes:
      - ./src/main/resources/credentials.json:/app/credentials.json
volumes:
  postgres_data: