spreadsheets:
  - id: "16c-SSNDJSQWj2jCHVWSoVOCnZMBbAHKAC3Tq5JOCi5U" #Управ
    ranges:
      - category: "LOCATIONS"
        explicit: []
      - category: "USERS"
        explicit: []
      - category: "ACTUAL_INCOME"
        explicit:
          - id: 1
            range: "'План-Факт 1'!BF4:BF4"
            label: "Варварская"
          - id: 2
            range: "'План-Факт 2'!BF4:BF4"
            label: "Чугунова"
          - id: 3
            range: "'План-Факт 3'!BF4:BF4"
            label: "Родионова"
          - id: 4
            range: "'План-Факт 4'!BF4:BF4"
            label: "Мещерский"
          - id: 5
            range: "'План-Факт 5'!BF4:BF4"
            label: "Богородского"
          - id: 6
            range: "'План-Факт 6'!BF4:BF4"
            label: "Воровского"
          - id: 7
            range: "'План-Факт 7'!BF4:BF4"
            label: "Краснодонцев"
          - id: 8
            range: "'План-Факт 8'!BF4:BF4"
            label: "Щербакова"
          - id: 9
            range: "'План-Факт 9'!BF4:BF4"
            label: "Лескова"


      - category: "PLAN_COMPLETION_PERCENT"
        explicit:
          - id: 1
            range: "'План-Факт 1'!BJ4:BJ4"
            label: "Варварская"
          - id: 2
            range: "'План-Факт 2'!BJ4:BJ4"
            label: "Чугунова"
          - id: 3
            range: "'План-Факт 3'!BJ4:BJ4"
            label: "Родионова"
          - id: 4
            range: "'План-Факт 4'!BJ4:BJ4"
            label: "Мещерский"
          - id: 5
            range: "'План-Факт 5'!BJ4:BJ4"
            label: "Богородского"
          - id: 6
            range: "'План-Факт 6'!BJ4:BJ4"
            label: "Воровского"
          - id: 7
            range: "'План-Факт 7'!BJ4:BJ4"
            label: "Краснодонцев"
          - id: 8
            range: "'План-Факт 8'!BJ4:BJ4"
            label: "Щербакова"
          - id: 9
            range: "'План-Факт 9'!BJ4:BJ4"
            label: "Лескова"

      - category: "LOCATION_PLAN"
        explicit:
          - id: 1
            range: "'План-Факт 1'!BF3:BF3"
            label: "Варварская"
          - id: 2
            range: "'План-Факт 2'!BF3:BF3"
            label: "Чугунова"
          - id: 3
            range: "'План-Факт 3'!BF3:BF3"
            label: "Родионова"
          - id: 4
            range: "'План-Факт 4'!BF3:BF3"
            label: "Мещерский"
          - id: 5
            range: "'План-Факт 5'!BF3:BF3"
            label: "Богородского"
          - id: 6
            range: "'План-Факт 6'!BF3:BF3"
            label: "Воровского"
          - id: 7
            range: "'План-Факт 7'!BF3:BF3"
            label: "Краснодонцев"
          - id: 8
            range: "'План-Факт 8'!BF3:BF3"
            label: "Щербакова"
          - id: 9
            range: "'План-Факт 9'!BF3:BF3"
            label: "Лескова"

      - category: "MAX_DAILY_REVENUE"
        explicit:
          - id: 1
            range: "'План-Факт 1'!BL100:BL100"
            label: "Варварская"
          - id: 2
            range: "'План-Факт 2'!BL100:BL100"
            label: "Чугунова"
          - id: 3
            range: "'План-Факт 3'!BL100:BL100"
            label: "Родионова"
          - id: 4
            range: "'План-Факт 4'!BL100:BL100"
            label: "Мещерский"
          - id: 5
            range: "'План-Факт 5'!BL100:BL100"
            label: "Богородского"
          - id: 6
            range: "'План-Факт 6'!BL100:BL100"
            label: "Воровского"
          - id: 7
            range: "'План-Факт 7'!BL100:BL100"
            label: "Краснодонцев"
          - id: 8
            range: "'План-Факт 8'!BL100:BL100"
            label: "Щербакова"
          - id: 9
            range: "'План-Факт 9'!BL100:BL100"
            label: "Лескова"

      - category: "REMAINING_TO_PLAN"
        explicit:
          - id: 1
            range: "'План-Факт 1'!BK50:BK50"
            label: "Варварская"
          - id: 2
            range: "'План-Факт 2'!BK50:BK50"
            label: "Чугунова"
          - id: 3
            range: "'План-Факт 3'!BK50:BK50"
            label: "Родионова"
          - id: 4
            range: "'План-Факт 4'!BK50:BK50"
            label: "Мещерский"
          - id: 5
            range: "'План-Факт 5'!BK50:BK50"
            label: "Богородского"
          - id: 6
            range: "'План-Факт 6'!BK50:BK50"
            label: "Воровского"
          - id: 7
            range: "'План-Факт 7'!BK50:BK50"
            label: "Краснодонцев"
          - id: 8
            range: "'План-Факт 8'!BK50:BK50"
            label: "Щербакова"
          - id: 9
            range: "'План-Факт 9'!BK50:BK50"
            label: "Лескова"

  - id: "1BwQdns8KkBsZ0C4k8dC6BtGxaLNocbmDR0bfuGKXSJs" #Показ админов
    ranges:
      - category: "LOCATIONS"
        explicit:
          - id: 1
            range: "'Пробные (команда Кати)'!D3:AG3"
          - id: 2
            range: "'Пробные (команда Кати)'!AH3:BK3"
          - id: 3
            range: "'Пробные (команда Кати)'!BL3:CO3"
          - id: 4
            range: "'Пробные (команда Кати)'!CP3:DS3"
          - id: 5
            range: "'Пробные (команда Кати)'!DT3:WE3"
          - id: 6
            range: "'Пробные (команда Алины)'!D3:AG3"
          - id: 7
            range: "'Пробные (команда Алины)'!AH3:BK3"
          - id: 8
            range: "'Пробные (команда Алины)'!BL3:CO3"
          - id: 9
            range: "'Пробные (команда Алины)'!CP3:DS3"

      - category: "USERS"
        explicit:
          - id: 1
            range: "'Пробные (команда Кати)'!C51:C51"
          - id: 2
            range: "'Пробные (команда Кати)'!C52:C52"
          - id: 3
            range: "'Пробные (команда Кати)'!C54:C54"
          - id: 4
            range: "'Пробные (команда Кати)'!C55:C55"
          - id: 5
            range: "'Пробные (команда Кати)'!C60:C60"
          - id: 6
            range: "'Пробные (команда Кати)'!C61:C61"
          - id: 7
            range: "'Пробные (команда Кати)'!C63:C63"
          - id: 8
            range: "'Пробные (команда Кати)'!C64:C64"
          - id: 9
            range: "'Пробные (команда Алины)'!C51:C51"
          - id: 10
            range: "'Пробные (команда Алины)'!C52:C52"
          - id: 11
            range: "'Пробные (команда Алины)'!C53:C53"
          - id: 12
            range: "'Пробные (команда Алины)'!C54:C54"
          - id: 13
            range: "'Пробные (команда Алины)'!C56:C56"
          - id: 14
            range: "'Пробные (команда Алины)'!C55:C55"
          - id: 15
            range: "'Пробные (команда Алины)'!C57:C57"
          - id: 16
            range: "'Пробные (команда Алины)'!C58:C58"

      - category: "CONVERSION_RATE"
        explicit:
          - id: 1
            range: "'Пробные (команда Кати)'!D51:D51"
            label: "Настя (Варварская)"
          - id: 2
            range: "'Пробные (команда Кати)'!D52:D52"
            label: "Женя (Варварская)"
          - id: 3
            range: "'Пробные (команда Кати)'!D54:D54"
            label: "Вика (Чугунова)"
          - id: 4
            range: "'Пробные (команда Кати)'!D55:D55"
            label: "Яна (Чугунова)"
          - id: 5
            range: "'Пробные (команда Кати)'!D60:D60"
            label: "Катя (Мещерский)"
          - id: 6
            range: "'Пробные (команда Кати)'!D61:D61"
            label: "Диана (Мещерский)"
          - id: 7
            range: "'Пробные (команда Кати)'!D63:D63"
            label: "Аня (Богородского)"
          - id: 8
            range: "'Пробные (команда Кати)'!D64:D64"
            label: "Лиза (Богородского)"
          - id: 9
            range: "'Пробные (команда Алины)'!D51:D51"
            label: "Полина (Воровского)"
          - id: 10
            range: "'Пробные (команда Алины)'!D52:D52"
            label: "Таня (Воровского)"
          - id: 11
            range: "'Пробные (команда Алины)'!D53:D53"
            label: "Софа (Краснодонцев)"
          - id: 12
            range: "'Пробные (команда Алины)'!D54:D54"
            label: "Юля (Краснодонцев)"
          - id: 13
            range: "'Пробные (команда Алины)'!D56:D56"
            label: "Маша (Щербакова)"
          - id: 14
            range: "'Пробные (команда Алины)'!D55:D55"
            label: "Вика (Щербакова)"
          - id: 15
            range: "'Пробные (команда Алины)'!D57:D57"
            label: "Арина(Лескова)"
          - id: 16
            range: "'Пробные (команда Алины)'!D58:D58"
            label: "Настя (Лескова)"

      - category: "PERSONAL_REVENUE"
        explicit:
          - id: 1
            range: "'Пробные (команда Кати)'!J51:J51"
            label: "Настя (Варварская)"
          - id: 2
            range: "'Пробные (команда Кати)'!J52:J52"
            label: "Женя (Варварская)"
          - id: 3
            range: "'Пробные (команда Кати)'!J54:J54"
            label: "Вика (Чугунова)"
          - id: 4
            range: "'Пробные (команда Кати)'!J55:J55"
            label: "Яна (Чугунова)"
          - id: 5
            range: "'Пробные (команда Кати)'!J60:J60"
            label: "Катя (Мещерский)"
          - id: 6
            range: "'Пробные (команда Кати)'!J61:J61"
            label: "Диана (Мещерский)"
          - id: 7
            range: "'Пробные (команда Кати)'!J63:J63"
            label: "Аня (Богородского)"
          - id: 8
            range: "'Пробные (команда Кати)'!J64:J64"
            label: "Лиза (Богородского)"
          - id: 9
            range: "'Пробные (команда Алины)'!J51:J51"
            label: "Полина (Воровского)"
          - id: 10
            range: "'Пробные (команда Алины)'!J52:J52"
            label: "Таня (Воровского)"
          - id: 11
            range: "'Пробные (команда Алины)'!J53:J53"
            label: "Софа (Краснодонцев)"
          - id: 12
            range: "'Пробные (команда Алины)'!J54:J54"
            label: "Юля (Краснодонцев)"
          - id: 13
            range: "'Пробные (команда Алины)'!J56:J56"
            label: "Маша (Щербакова)"
          - id: 14
            range: "'Пробные (команда Алины)'!J55:J55"
            label: "Вика (Щербакова)"
          - id: 15
            range: "'Пробные (команда Алины)'!J57:J57"
            label: "Арина(Лескова)"
          - id: 16
            range: "'Пробные (команда Алины)'!J58:J58"
            label: "Настя (Лескова)"


#  - id: "1QcOiHd5pY3wxMtGvkeGMd7z826RQotHBWZ6u_mWWFg0"
#
#  - id: "1rFLR_5Zb43AVQedKCKcFXyLmO42Qt1CFMNHAqiFW8FU"